garuda_server:	13CS10049_ass4_garuda_server.cpp
				g++ -o garuda_server 13CS10049_ass4_garuda_server.cpp

client: 13CS10049_ass4_garuda_client.cpp
				g++ -o client 13CS10049_ass4_garuda_client.cpp

all: garuda_server client